### ISSUE TITLE
elex-solver error on install

### ISSUE THREAD

**Issue by mtdukes** [washingtonpost/elex-live-model#6]
Howdy folks. I'm getting the following error in the CLI on `pip install elex-model`:

> ERROR: Could not find a version that satisfies the requirement elex-solver<1 (from elex-model) (from versions: 1.0.2)
> ERROR: No matching distribution found for elex-solver<1

Looks like the updated code in the repo for setup.py has `elex-solver<2` listed in `INSTALL_REQUIRES`?

**Comment by emilyliu7321** [comment]
We actually just released a fix for this in version 1.0.5!

**Comment by mtdukes** [comment]
Confirmed! Fastest issue close ever!
